import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LayoutWrapper from './layoutWrapper'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TradeIt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutWrapper children={children}></LayoutWrapper>
      </body>
    </html>
  )
}
